# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lootprotocol < Formula
  desc "CLI for the Loot Protocol AI Extension Marketplace"
  homepage "https://lootprotocol.com"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lootprotocol/lootprotocol/releases/download/v0.2.1/lootprotocol_0.2.1_darwin_amd64.tar.gz"
      sha256 "db3b2e9fcdbf3cc139fdc70225552df03955e930e56b41e85bc3f9fd448337c7"

      define_method(:install) do
        bin.install "lootprotocol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lootprotocol/lootprotocol/releases/download/v0.2.1/lootprotocol_0.2.1_darwin_arm64.tar.gz"
      sha256 "ece9c78899cf372522382708c5a7a7f2b9c8d51a8fc81fa165ac3d484336f12e"

      define_method(:install) do
        bin.install "lootprotocol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lootprotocol/lootprotocol/releases/download/v0.2.1/lootprotocol_0.2.1_linux_amd64.tar.gz"
      sha256 "267ff5bc18882aaba98b1e62be04f6c3e508100a3447755a35c079f130d8f7c9"
      define_method(:install) do
        bin.install "lootprotocol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lootprotocol/lootprotocol/releases/download/v0.2.1/lootprotocol_0.2.1_linux_arm64.tar.gz"
      sha256 "83750fe5f9c8d809913809526d76999565a7168ab09890050e19142d06b88e14"
      define_method(:install) do
        bin.install "lootprotocol"
      end
    end
  end

  test do
    system "#{bin}/lootprotocol", "--version"
  end
end
