# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lootprotocol < Formula
  desc "CLI for the Loot Protocol AI Extension Marketplace"
  homepage "https://lootprotocol.com"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lootprotocol/lootprotocol/releases/download/v0.2.0/lootprotocol_0.2.0_darwin_amd64.tar.gz"
      sha256 "f15d70f03116b08164f2dbfca912db7072776238edfe97c8a44abaf8c572961d"

      define_method(:install) do
        bin.install "lootprotocol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lootprotocol/lootprotocol/releases/download/v0.2.0/lootprotocol_0.2.0_darwin_arm64.tar.gz"
      sha256 "eb46b4aae1138997e28b231e39cfba80c3666712b5743eae837e337a9b8c2116"

      define_method(:install) do
        bin.install "lootprotocol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lootprotocol/lootprotocol/releases/download/v0.2.0/lootprotocol_0.2.0_linux_amd64.tar.gz"
      sha256 "2f7e3a0cb9c705b1dd02dc60e40376ef0c419b7eeb2b7a806a2a5d939bf5c7b4"
      define_method(:install) do
        bin.install "lootprotocol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lootprotocol/lootprotocol/releases/download/v0.2.0/lootprotocol_0.2.0_linux_arm64.tar.gz"
      sha256 "e4d588f64e3d1b7cbc6f4af6cba1648b5a1fb55b38b34e54208bad6e789328ba"
      define_method(:install) do
        bin.install "lootprotocol"
      end
    end
  end

  test do
    system "#{bin}/lootprotocol", "--version"
  end
end
