# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loot < Formula
  desc "CLI for the Loot Protocol AI Extension Marketplace"
  homepage "https://lootprotocol.com"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lootprotocol/loot-releases/releases/download/v0.4.0/lootprotocol_0.4.0_darwin_amd64.tar.gz"
      sha256 "50f6d0a38a484dc6957cd8c288dd93c955eb413af6b684032b785d890107c124"

      define_method(:install) do
        bin.install "loot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lootprotocol/loot-releases/releases/download/v0.4.0/lootprotocol_0.4.0_darwin_arm64.tar.gz"
      sha256 "b0ce13dd31849c74f7a5d2680c989f5f06b37a1368e6fb819bd8497c25c56f00"

      define_method(:install) do
        bin.install "loot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lootprotocol/loot-releases/releases/download/v0.4.0/lootprotocol_0.4.0_linux_amd64.tar.gz"
      sha256 "2151d94ecd0bbb7b66d723546962b756d8e0bff60008a990e14c03bdd6079527"
      define_method(:install) do
        bin.install "loot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lootprotocol/loot-releases/releases/download/v0.4.0/lootprotocol_0.4.0_linux_arm64.tar.gz"
      sha256 "1151d7bafef0f78a090b19b324808df4aecac5b09c6ceb598cc52427f6cef569"
      define_method(:install) do
        bin.install "loot"
      end
    end
  end

  test do
    system "#{bin}/loot", "--version"
  end
end
