# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lootprotocol < Formula
  desc "CLI for the Loot Protocol AI Extension Marketplace"
  homepage "https://lootprotocol.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lootprotocol/lootprotocol/releases/download/v0.1.0/lootprotocol_0.1.0_darwin_amd64.tar.gz"
      sha256 "552aa64e3cb5a3b60e83f8209e92238e69efb98a03afe751c4c6ab80956f2ad2"

      define_method(:install) do
        bin.install "lootprotocol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lootprotocol/lootprotocol/releases/download/v0.1.0/lootprotocol_0.1.0_darwin_arm64.tar.gz"
      sha256 "7c036f076a4dcac0792ec09e1769af9d8ff9206993f411093ab7e80226e3c315"

      define_method(:install) do
        bin.install "lootprotocol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lootprotocol/lootprotocol/releases/download/v0.1.0/lootprotocol_0.1.0_linux_amd64.tar.gz"
      sha256 "238b0c64aac87a537977fa2f1c01e522a7ccc278a520cbc3bb9ca8ef7ed0018d"
      define_method(:install) do
        bin.install "lootprotocol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lootprotocol/lootprotocol/releases/download/v0.1.0/lootprotocol_0.1.0_linux_arm64.tar.gz"
      sha256 "17fbddb6d5555d6da0f20ff511d7e59c386d9182654f088ae1664d95de3a3793"
      define_method(:install) do
        bin.install "lootprotocol"
      end
    end
  end

  test do
    system "#{bin}/lootprotocol", "--version"
  end
end
