# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loot < Formula
  desc "CLI for the Loot Protocol AI Extension Marketplace"
  homepage "https://lootprotocol.com"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lootprotocol/lootprotocol/releases/download/v0.3.1/lootprotocol_0.3.1_darwin_amd64.tar.gz"
      sha256 "877642555c2aaef40cc9d9c41553713e2da24e95dd9926ea05b28f32c65b78ae"

      define_method(:install) do
        bin.install "loot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lootprotocol/lootprotocol/releases/download/v0.3.1/lootprotocol_0.3.1_darwin_arm64.tar.gz"
      sha256 "b47660a35cbcac2886b15fcd3c12c965e44d6479565923036c04ff978f0aa6ea"

      define_method(:install) do
        bin.install "loot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lootprotocol/lootprotocol/releases/download/v0.3.1/lootprotocol_0.3.1_linux_amd64.tar.gz"
      sha256 "e2ff2df1a722b8a40eabbb3d90bc7476a50a2e660b494a84df239eed98681c1b"
      define_method(:install) do
        bin.install "loot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lootprotocol/lootprotocol/releases/download/v0.3.1/lootprotocol_0.3.1_linux_arm64.tar.gz"
      sha256 "ef2becdad634f45ce2888e07370efeeb79e47ec6fefb50c68a9a4f140c04c893"
      define_method(:install) do
        bin.install "loot"
      end
    end
  end

  test do
    system "#{bin}/loot", "--version"
  end
end
