# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loot < Formula
  desc "CLI for the Loot Protocol AI Extension Marketplace"
  homepage "https://lootprotocol.com"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lootprotocol/loot-releases/releases/download/v0.5.0/lootprotocol_0.5.0_darwin_amd64.tar.gz"
      sha256 "7214fe323c02c2ce21ccd8d1928336eabb10dfe13aaee305c87821f2fe0a7ec5"

      define_method(:install) do
        bin.install "loot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lootprotocol/loot-releases/releases/download/v0.5.0/lootprotocol_0.5.0_darwin_arm64.tar.gz"
      sha256 "04cab1034b380e480fea9d9765459e1baaeccd90da12d1e42649e2790937afa5"

      define_method(:install) do
        bin.install "loot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lootprotocol/loot-releases/releases/download/v0.5.0/lootprotocol_0.5.0_linux_amd64.tar.gz"
      sha256 "7b742153275c69f5cc3a53cdcac178cb34c9f7e40700729b7b04929e0deec15c"
      define_method(:install) do
        bin.install "loot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lootprotocol/loot-releases/releases/download/v0.5.0/lootprotocol_0.5.0_linux_arm64.tar.gz"
      sha256 "af82acf4d0428bef3b35b2b64fb7027bdbb8d64bbbc69b77b5336c344125bab5"
      define_method(:install) do
        bin.install "loot"
      end
    end
  end

  test do
    system "#{bin}/loot", "--version"
  end
end
